# Generated by Django 3.1 on 2020-10-06 04:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('reading_type', models.CharField(choices=[('kunyomi', 'kunyomi'), ('onyomi', 'onyomi'), ('vocabulary', 'vocabulary')], default='vocabulary', max_length=64)),
                ('pronunciation', models.CharField(max_length=128, unique=True)),
                ('furigana', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'reading',
                'verbose_name_plural': 'readings',
                'ordering': ['reading_type', 'pronunciation'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'source',
                'verbose_name_plural': 'sources',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('topic_type', models.CharField(choices=[('grammar', 'grammar'), ('kanji', 'kanji'), ('katakana', 'katakana'), ('hiragana', 'hiragana'), ('vocabulary', 'vocabulary'), ('compounding', 'compounding')], default='general', max_length=120)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('show_furigana', models.BooleanField(default=False)),
                ('reading', models.ManyToManyField(blank=True, related_name='topic_reading', to='api.Reading')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='api.source')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
                'ordering': ['topic_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(max_length=128)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.topic')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['topic', 'notes'],
            },
        ),
    ]
